### ISSUE TITLE
 Implement Keyboard Shortcuts for Tools

### ISSUE THREAD

**Issue by codewarnab** [codewarnab/paint-web-app#3]
### Overview
Introduce keyboard shortcuts to expedite tool selection and streamline user interaction within the app.

### Goals
- Enhance user workflow by enabling quick tool access via keyboard shortcuts.
- Improve accessibility and efficiency for users accustomed to shortcut-based navigation.

### Approach
- Assign intuitive and convenient key combinations to essential tools.
- Ensure compatibility across multiple devices and browsers.

### Outcomes
- Accelerated tool selection and usage through keyboard-driven commands.
- Increased user convenience and productivity within the application.

### Note
This enhancement aligns with our commitment to optimizing user interaction and accessibility.

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by codewarnab** [comment]
> Hey, I would like to take this up

ok then i can i assign you this issue
